trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- task: Docker@2
  inputs:
    containerRegistry: '<nombre-registro>'
    repository: 'fastapi-bcr'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '<nombre-conexion>'
    appName: '<nombre-app>'
    containers: 'fastapi-bcr:$(Build.BuildId)'
