version: "3.9"

services:
  validacion-bcr-api:
    build: .
    container_name: validacion-bcr-api
    ports:
      - "8100:8100"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
