version: '3.8'

services:
  sentinel:
    build: .
    container_name: sentinel-dashboard
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
      - ./backups:/app/backups
    environment:
      - SENTINEL_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - sentinel-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sentinel.rule=Host(`sentinel.bcr.local`)"
      - "traefik.http.services.sentinel.loadbalancer.server.port=8080"

  redis:
    image: redis:7-alpine
    container_name: sentinel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - sentinel-network
    command: redis-server --appendonly yes

  influxdb:
    image: influxdb:2.7-alpine
    container_name: sentinel-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=sentinel
      - DOCKER_INFLUXDB_INIT_PASSWORD=sentinel123
      - DOCKER_INFLUXDB_INIT_ORG=bcr
      - DOCKER_INFLUXDB_INIT_BUCKET=network_metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=sentinel-admin-token
    restart: unless-stopped
    networks:
      - sentinel-network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: sentinel-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=sentinel123
      - GF_INSTALL_PLUGINS=grafana-influxdb-datasource
    restart: unless-stopped
    networks:
      - sentinel-network

  nginx:
    image: nginx:alpine
    container_name: sentinel-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - sentinel
    restart: unless-stopped
    networks:
      - sentinel-network

networks:
  sentinel-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local
  grafana_data:
    driver: local
